AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: |
  Three different SageMaker endpoints running the YOLOv8 object detection model.

Parameters:
  MyCustomImage:
    Description: ARN of custom image to use
    Type: String
  EndpointInstanceType:
    Description: What instance type to use for the endpoint
    Type: String
    Default: ml.g5.xlarge # GPU instance
  AyncS3UriOutput: # Only required for the async endpoints
    Description: S3 bucket and prefix to store async inference output
    Type: String

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-model.html#aws-resource-sagemaker-model-syntax
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        Image: !Ref MyCustomImage

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpointconfig.html
  RealtimeEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Sub YOLOv8-${AWS::StackName}
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: !Ref EndpointInstanceType
          ModelName: !GetAtt SageMakerModel.ModelName
          VariantName: AllTrafficVariant

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpoint.html
  MyYoloV8Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !GetAtt RealtimeEndpointConfig.EndpointConfigName
      Tags:
        - Key: project
          Value: demo

  AsyncEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Sub YOLOv8-${AWS::StackName}-async
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: !Ref EndpointInstanceType
          ModelName: !GetAtt SageMakerModel.ModelName
          VariantName: AllTrafficVariant
      AsyncInferenceConfig:
        OutputConfig:
          S3OutputPath: !Ref AyncS3UriOutput

  MyAsyncYoloV8Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !GetAtt AsyncEndpointConfig.EndpointConfigName
      Tags:
        - Key: project
          Value: demo

  ServerlessEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Sub YOLOv8-${AWS::StackName}-serverless
      ProductionVariants:
        - InitialVariantWeight: 1.0
          ModelName: !GetAtt SageMakerModel.ModelName
          VariantName: AllTrafficVariant
          ServerlessConfig:
            MaxConcurrency: 4
            MemorySizeInMB: 5120

  # MyServerlessYoloV8Endpoint:
  #   Type: AWS::SageMaker::Endpoint
  #   Properties:
  #     EndpointConfigName: !GetAtt ServerlessEndpointConfig.EndpointConfigName
  #     Tags:
  #       - Key: project
  #         Value: demo

  # Role used by the endpoint to fetch Docker Image, read/write to S3 and Cloudwatch logs etc.
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: SageMakerExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:*
                  - s3:*
                  - logs:*
                  - cloudwatch:*
                  - ecr:*
                Resource: "*"

Outputs:
  EndpointName:
    Value: !GetAtt MyYoloV8Endpoint.EndpointName
  AsyncEndpointName:
    Value: !GetAtt MyAsyncYoloV8Endpoint.EndpointName
  ServerlessEndpointName:
    Value: !GetAtt MyServerlessYoloV8Endpoint.EndpointName
