AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: |
  Three different SageMaker endpoints running the YOLOv9 object detection model.

Parameters:
  MyCustomImage:
    Description: ARN of custom image to use
    Type: String
  EndpointInstanceType:
    Description: What instance type to use for the endpoint
    Type: String
    Default: ml.g5.xlarge # GPU instance
  AyncS3UriOutput: # Only required for the async endpoints
    Description: S3 bucket and prefix to store async inference output
    Type: String

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-model.html#aws-resource-sagemaker-model-syntax
  YoloV9Model:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        Image: !Ref MyCustomImage

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpointconfig.html
  Yolov9RealtimeEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: !Ref EndpointInstanceType
          ModelName: !GetAtt YoloV9Model.ModelName
          VariantName: AllTrafficVariant

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpoint.html
  MyYoloV9Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !GetAtt Yolov9RealtimeEndpointConfig.EndpointConfigName
      DeploymentConfig:
        AutoRollbackConfiguration:
          Alarms:
            - AlarmName: !Ref SageMakerEndpointAlarm # If this goes into alarm during deployment, roll back the deployment
        BlueGreenUpdatePolicy:
          TerminationWaitInSeconds: 300 # How long should we keep the old endpoint live "just in case" after a successfull deployment
          TrafficRoutingConfiguration:
            Type: ALL_AT_ONCE
      Tags:
        - Key: project
          Value: demo

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html
  SagemakerEndpointAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Monitor errors from a SageMaker endpoint
      AlarmName: !Sub "SageMakerEndpointAlarm-${AWS::StackName}"
      Namespace: AWS/SageMaker
      MetricName: InvocationModelErrors
      Dimensions:
        - Name: EndpointName
          Value: !GetAtt MyYoloV9Endpoint.EndpointName
        - Name: VariantName
          Value: AllTrafficVariant
      Statistic: Sum
      Period: 30
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  Yolov9AsyncEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: !Ref EndpointInstanceType
          ModelName: !GetAtt YoloV9Model.ModelName
          VariantName: AllTrafficVariant
      AsyncInferenceConfig:
        OutputConfig:
          S3OutputPath: !Ref AyncS3UriOutput

  MyAsyncYoloV9Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !GetAtt Yolov9AsyncEndpointConfig.EndpointConfigName
      Tags:
        - Key: project
          Value: demo

  Yolov9ServerlessEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialVariantWeight: 1.0
          ModelName: !GetAtt YoloV9Model.ModelName
          VariantName: AllTrafficVariant
          ServerlessConfig:
            MaxConcurrency: 4
            MemorySizeInMB: 5120

  # MyServerlessYoloV9Endpoint:
  #   Type: AWS::SageMaker::Endpoint
  #   Properties:
  #     EndpointConfigName: !GetAtt Yolov9ServerlessEndpointConfig.EndpointConfigName
  #     Tags:
  #       - Key: project
  #         Value: demo

  # Role used by the endpoint to fetch Docker Image, read/write to S3 and Cloudwatch logs etc.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: SageMakerExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:*
                  - s3:*
                  - logs:*
                  - cloudwatch:*
                  - ecr:*
                Resource: "*"

Outputs:
  EndpointName:
    Value: !GetAtt MyYoloV9Endpoint.EndpointName
  AsyncEndpointName:
    Value: !GetAtt MyAsyncYoloV9Endpoint.EndpointName
  # ServerlessEndpointName:
  #   Value: !GetAtt MyServerlessYoloV9Endpoint.EndpointName
