AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: |
  Three different SageMaker endpoint types for demo purposes.

Parameters:
  MyCustomImage:
    Description: ARN of custom image to use
    Type: String
  MyExecutionRole:
    Description: ARN of execution role for the endpoint
    Type: String
  ModelS3Uri:
    Description: S3 uri of Gzipped model archive.
    Type: String
  EndpointInstanceType:
    Description: What instance type to use for the endpoint
    Type: String
    Default: ml.g5.xlarge # GPU instance
  # OutputBucket:
  #   Description: S3 bucket to store async inference output
  #   Type: String

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-model.html#aws-resource-sagemaker-model-syntax
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Sub YOLOv8-${AWS::StackName}
      ExecutionRoleArn: !Ref MyExecutionRole
      PrimaryContainer:
        Image: !Ref MyCustomImage
        ModelDataSource:
          S3DataSource:
            S3Uri: !Ref ModelS3Uri
            S3DataType: S3Prefix
            CompressionType: Gzip

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpointconfig.html
  RealtimeEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Sub YOLOv8-${AWS::StackName}
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: !Ref EndpointInstanceType
          ModelName: !GetAtt SageMakerModel.ModelName
          VariantName: AllTrafficVariant

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpoint.html
  MyYoloV8Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !GetAtt RealtimeEndpointConfig.EndpointConfigName
      Tags:
        - Key: project
          Value: demo

  # AsyncEndpointConfig:
  #   Type: AWS::SageMaker::EndpointConfig
  #   Properties:
  #     EndpointConfigName: !Sub YOLOv8-${AWS::StackName}-async
  #     AsyncInferenceConfig:
  #       OutputConfig:
  #         S3OutputPath: !Sub s3://${OutputBucket}-async-inference-output/ # Add parameter for OutputBucket

  # MyAsyncYoloV8Endpoint:
  #   Type: AWS::SageMaker::Endpoint
  #   Properties:
  #     EndpointConfigName: !GetAtt AsyncEndpointConfig.EndpointConfigName
  #     Tags:
  #       - Key: project
  #         Value: demo

  # ServerlessEndpointConfig:
  #   Type: AWS::SageMaker::EndpointConfig
  #   Properties:
  #     EndpointConfigName: !Sub YOLOv8-${AWS::StackName}-serverless
  #     ProductionVariants:
  #       - InitialVariantWeight: 1.0
  #         ModelName: !GetAtt SageMakerModel.ModelName
  #         VariantName: AllTrafficVariant
  #         ServerlessConfig:
  #           MaxConcurrency: 4
  #           MemorySizeInMB: 5120

  # MyServerlessYoloV8Endpoint:
  #   Type: AWS::SageMaker::Endpoint
  #   Properties:
  #     EndpointConfigName: !GetAtt ServerlessEndpointConfig.EndpointConfigName
  #     Tags:
  #       - Key: project
  #         Value: demo

Outputs:
  EndpointName:
    Value: !GetAtt MyYoloV8Endpoint.EndpointName
  # AsyncEndpointName:
  #   Value: !GetAtt MyAsyncYoloV8Endpoint.EndpointName
  # ServerlessEndpointName:
  #   Value: !GetAtt MyServerlessYoloV8Endpoint.EndpointName
