name: Deploy SageMaker endpoint
on:
  push:
    branches:
      - main
    paths:
      - cloudformation/**
      - .github/workflows/deploy_endpoint.yml

env:
  AWS_REGION: "eu-west-1"
  REPO: ${{github.event.repository.name}}
  ECR_REPOSITORY: yolov9 # Name of ECR repo to hold custom Docker image
  OIDC_ROLE: arn:aws:iam::934765130326:role/github-actions-role # What role to assume in AWS
  S3_ASYNC_OUTPUT: s3://mlbucket13/yolov9/async/output/ # Where to store async inference result
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  DeployPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{env.OIDC_ROLE}}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Build and deploy CFN
        env:
          ENVIRONMENT: prod
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          sam build --use-container
          sam deploy --stack-name ${{env.REPO}} \
            --parameter-overrides \
              MyCustomImage=${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:latest \
              AyncS3UriOutput=${{env.S3_ASYNC_OUTPUT}} \
            --resolve-s3 \
            --region ${{env.AWS_REGION}} \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --tags project=yolov9 environment=${{env.ENVIRONMENT}}
